import type { Region } from "../src/tools/seats-aero/types";

/**
 * Maps every country name that appears in OpenFlights' `airports.dat` to one
 * of the six `Region` values, using standard continent conventions. Built by
 * fetching the live dataset and extracting all 237 distinct `Country` values
 * (verified 2026-08 — see `ingest-airports.ts`'s `main()`, which throws
 * listing any unmapped country so this table cannot silently drift out of
 * sync with the source data).
 *
 * OpenFlights uses full country names, not ISO codes, and lists overseas
 * territories as their own "country" entries (e.g. "Guadeloupe", "Reunion",
 * "Hong Kong") rather than nesting them under the administering country —
 * each is mapped here by its own geography, not its sovereign's.
 *
 * A few deliberate, non-obvious calls:
 * - Russia -> Europe, Turkey -> Europe, Cyprus -> Europe: political/aviation
 *   convention (and, for Turkey, consistent with this project's existing
 *   MAJOR_HUBS table treating Istanbul as a European hub).
 * - Armenia, Azerbaijan, Georgia (the Caucasus) -> Asia, and Kazakhstan ->
 *   Asia: UN M49 statistical geoscheme (Western/Central Asia).
 * - "Antarctica" -> South America: the one IATA-coded Antarctic airport in
 *   the dataset (Teniente R. Marsh, TNM) is Chilean-operated and reached via
 *   Punta Arenas, Chile — there is no seventh "Antarctica" Region value.
 * - Christmas Island, Cocos (Keeling) Islands -> Oceania; British Indian
 *   Ocean Territory -> Africa: standard continent groupings for these
 *   Indian Ocean territories.
 */
export const COUNTRY_TO_REGION: Record<string, Region> = {
  // North America (incl. Central America, the Caribbean, and Greenland)
  Anguilla: "North America",
  "Antigua and Barbuda": "North America",
  Aruba: "North America",
  Bahamas: "North America",
  Barbados: "North America",
  Belize: "North America",
  Bermuda: "North America",
  "British Virgin Islands": "North America",
  Canada: "North America",
  "Cayman Islands": "North America",
  "Costa Rica": "North America",
  Cuba: "North America",
  Dominica: "North America",
  "Dominican Republic": "North America",
  "El Salvador": "North America",
  Greenland: "North America",
  Grenada: "North America",
  Guadeloupe: "North America",
  Guatemala: "North America",
  Haiti: "North America",
  Honduras: "North America",
  Jamaica: "North America",
  Martinique: "North America",
  Mexico: "North America",
  Montserrat: "North America",
  "Netherlands Antilles": "North America",
  Nicaragua: "North America",
  Panama: "North America",
  "Puerto Rico": "North America",
  "Saint Kitts and Nevis": "North America",
  "Saint Lucia": "North America",
  "Saint Pierre and Miquelon": "North America",
  "Saint Vincent and the Grenadines": "North America",
  "Trinidad and Tobago": "North America",
  "Turks and Caicos Islands": "North America",
  "United States": "North America",
  "Virgin Islands": "North America",

  // South America
  Antarctica: "South America",
  Argentina: "South America",
  Bolivia: "South America",
  Brazil: "South America",
  Chile: "South America",
  Colombia: "South America",
  Ecuador: "South America",
  "Falkland Islands": "South America",
  "French Guiana": "South America",
  Guyana: "South America",
  Paraguay: "South America",
  Peru: "South America",
  Suriname: "South America",
  Uruguay: "South America",
  Venezuela: "South America",

  // Europe
  Albania: "Europe",
  Austria: "Europe",
  Belarus: "Europe",
  Belgium: "Europe",
  "Bosnia and Herzegovina": "Europe",
  Bulgaria: "Europe",
  Croatia: "Europe",
  Cyprus: "Europe",
  "Czech Republic": "Europe",
  Denmark: "Europe",
  Estonia: "Europe",
  "Faroe Islands": "Europe",
  Finland: "Europe",
  France: "Europe",
  Germany: "Europe",
  Gibraltar: "Europe",
  Greece: "Europe",
  Guernsey: "Europe",
  Hungary: "Europe",
  Iceland: "Europe",
  Ireland: "Europe",
  "Isle of Man": "Europe",
  Italy: "Europe",
  Jersey: "Europe",
  Latvia: "Europe",
  Lithuania: "Europe",
  Luxembourg: "Europe",
  Macedonia: "Europe",
  Malta: "Europe",
  Moldova: "Europe",
  Montenegro: "Europe",
  Netherlands: "Europe",
  Norway: "Europe",
  Poland: "Europe",
  Portugal: "Europe",
  Romania: "Europe",
  Russia: "Europe",
  Serbia: "Europe",
  Slovakia: "Europe",
  Slovenia: "Europe",
  Spain: "Europe",
  Svalbard: "Europe",
  Sweden: "Europe",
  Switzerland: "Europe",
  Turkey: "Europe",
  Ukraine: "Europe",
  "United Kingdom": "Europe",

  // Africa
  Algeria: "Africa",
  Angola: "Africa",
  Benin: "Africa",
  Botswana: "Africa",
  "British Indian Ocean Territory": "Africa",
  "Burkina Faso": "Africa",
  Burundi: "Africa",
  Cameroon: "Africa",
  "Cape Verde": "Africa",
  "Central African Republic": "Africa",
  Chad: "Africa",
  Comoros: "Africa",
  "Congo (Brazzaville)": "Africa",
  "Congo (Kinshasa)": "Africa",
  "Cote d'Ivoire": "Africa",
  Djibouti: "Africa",
  Egypt: "Africa",
  "Equatorial Guinea": "Africa",
  Eritrea: "Africa",
  Ethiopia: "Africa",
  Gabon: "Africa",
  Gambia: "Africa",
  Ghana: "Africa",
  Guinea: "Africa",
  "Guinea-Bissau": "Africa",
  Kenya: "Africa",
  Lesotho: "Africa",
  Liberia: "Africa",
  Libya: "Africa",
  Madagascar: "Africa",
  Malawi: "Africa",
  Mali: "Africa",
  Mauritania: "Africa",
  Mauritius: "Africa",
  Mayotte: "Africa",
  Morocco: "Africa",
  Mozambique: "Africa",
  Namibia: "Africa",
  Niger: "Africa",
  Nigeria: "Africa",
  Reunion: "Africa",
  Rwanda: "Africa",
  "Saint Helena": "Africa",
  "Sao Tome and Principe": "Africa",
  Senegal: "Africa",
  Seychelles: "Africa",
  "Sierra Leone": "Africa",
  Somalia: "Africa",
  "South Africa": "Africa",
  "South Sudan": "Africa",
  Sudan: "Africa",
  Swaziland: "Africa",
  Tanzania: "Africa",
  Togo: "Africa",
  Tunisia: "Africa",
  Uganda: "Africa",
  "Western Sahara": "Africa",
  Zambia: "Africa",
  Zimbabwe: "Africa",

  // Asia (incl. the Middle East, the Caucasus, and Central Asia)
  Afghanistan: "Asia",
  Armenia: "Asia",
  Azerbaijan: "Asia",
  Bahrain: "Asia",
  Bangladesh: "Asia",
  Bhutan: "Asia",
  Brunei: "Asia",
  Burma: "Asia",
  Cambodia: "Asia",
  China: "Asia",
  "East Timor": "Asia",
  Georgia: "Asia",
  "Hong Kong": "Asia",
  India: "Asia",
  Indonesia: "Asia",
  Iran: "Asia",
  Iraq: "Asia",
  Israel: "Asia",
  Japan: "Asia",
  Jordan: "Asia",
  Kazakhstan: "Asia",
  Kuwait: "Asia",
  Kyrgyzstan: "Asia",
  Laos: "Asia",
  Lebanon: "Asia",
  Macau: "Asia",
  Malaysia: "Asia",
  Maldives: "Asia",
  Mongolia: "Asia",
  Myanmar: "Asia",
  Nepal: "Asia",
  "North Korea": "Asia",
  Oman: "Asia",
  Pakistan: "Asia",
  Palestine: "Asia",
  Philippines: "Asia",
  Qatar: "Asia",
  "Saudi Arabia": "Asia",
  Singapore: "Asia",
  "South Korea": "Asia",
  "Sri Lanka": "Asia",
  Syria: "Asia",
  Taiwan: "Asia",
  Tajikistan: "Asia",
  Thailand: "Asia",
  Turkmenistan: "Asia",
  "United Arab Emirates": "Asia",
  Uzbekistan: "Asia",
  Vietnam: "Asia",
  "West Bank": "Asia",
  Yemen: "Asia",

  // Oceania (incl. Australia, New Zealand, and Pacific island states/territories)
  "American Samoa": "Oceania",
  Australia: "Oceania",
  "Christmas Island": "Oceania",
  "Cocos (Keeling) Islands": "Oceania",
  "Cook Islands": "Oceania",
  Fiji: "Oceania",
  "French Polynesia": "Oceania",
  Guam: "Oceania",
  "Johnston Atoll": "Oceania",
  Kiribati: "Oceania",
  "Marshall Islands": "Oceania",
  Micronesia: "Oceania",
  "Midway Islands": "Oceania",
  Nauru: "Oceania",
  "New Caledonia": "Oceania",
  "New Zealand": "Oceania",
  Niue: "Oceania",
  "Norfolk Island": "Oceania",
  "Northern Mariana Islands": "Oceania",
  Palau: "Oceania",
  "Papua New Guinea": "Oceania",
  Samoa: "Oceania",
  "Solomon Islands": "Oceania",
  Tonga: "Oceania",
  Tuvalu: "Oceania",
  Vanuatu: "Oceania",
  "Wake Island": "Oceania",
  "Wallis and Futuna": "Oceania",
};
