import type { Region } from "../seats-aero/types";
import generatedAirports from "./airports.generated.json";

export type Airport = {
  iata: string;
  city: string;
  country: string;
  region: Region;
};

/**
 * ~6,000 IATA-coded commercial airports, generated by `npm run ingest:airports`
 * from OpenFlights (https://openflights.org/data.php, ODbL — source acknowledged
 * per license terms). Do not hand-edit; regenerate via the script instead.
 */
export const AIRPORTS: readonly Airport[] = generatedAirports as Airport[];

/**
 * Small hand-curated subset of major hubs, used only to pick sensible
 * representative airports for a region search (Task 2.1 Step 4) — the full
 * generated AIRPORTS table above carries no size/traffic signal.
 */
export const MAJOR_HUBS: readonly Airport[] = [
  // North America
  { iata: "ORD", city: "Chicago", country: "United States", region: "North America" },
  { iata: "JFK", city: "New York", country: "United States", region: "North America" },
  { iata: "LAX", city: "Los Angeles", country: "United States", region: "North America" },
  { iata: "SFO", city: "San Francisco", country: "United States", region: "North America" },
  { iata: "DFW", city: "Dallas", country: "United States", region: "North America" },
  { iata: "ATL", city: "Atlanta", country: "United States", region: "North America" },
  { iata: "YYZ", city: "Toronto", country: "Canada", region: "North America" },
  { iata: "MEX", city: "Mexico City", country: "Mexico", region: "North America" },

  // Europe
  { iata: "LHR", city: "London", country: "United Kingdom", region: "Europe" },
  { iata: "CDG", city: "Paris", country: "France", region: "Europe" },
  { iata: "FRA", city: "Frankfurt", country: "Germany", region: "Europe" },
  { iata: "AMS", city: "Amsterdam", country: "Netherlands", region: "Europe" },
  { iata: "MAD", city: "Madrid", country: "Spain", region: "Europe" },
  { iata: "FCO", city: "Rome", country: "Italy", region: "Europe" },
  { iata: "IST", city: "Istanbul", country: "Turkey", region: "Europe" },

  // Asia
  { iata: "NRT", city: "Tokyo", country: "Japan", region: "Asia" },
  { iata: "HND", city: "Tokyo", country: "Japan", region: "Asia" },
  { iata: "ICN", city: "Seoul", country: "South Korea", region: "Asia" },
  { iata: "PVG", city: "Shanghai", country: "China", region: "Asia" },
  { iata: "HKG", city: "Hong Kong", country: "Hong Kong", region: "Asia" },
  { iata: "SIN", city: "Singapore", country: "Singapore", region: "Asia" },
  { iata: "BKK", city: "Bangkok", country: "Thailand", region: "Asia" },
  { iata: "DXB", city: "Dubai", country: "United Arab Emirates", region: "Asia" },
  { iata: "DOH", city: "Doha", country: "Qatar", region: "Asia" },

  // Oceania
  { iata: "SYD", city: "Sydney", country: "Australia", region: "Oceania" },
  { iata: "MEL", city: "Melbourne", country: "Australia", region: "Oceania" },
  { iata: "AKL", city: "Auckland", country: "New Zealand", region: "Oceania" },

  // South America
  { iata: "GRU", city: "Sao Paulo", country: "Brazil", region: "South America" },
  { iata: "EZE", city: "Buenos Aires", country: "Argentina", region: "South America" },
  { iata: "SCL", city: "Santiago", country: "Chile", region: "South America" },
  { iata: "LIM", city: "Lima", country: "Peru", region: "South America" },
  { iata: "BOG", city: "Bogota", country: "Colombia", region: "South America" },

  // Africa
  { iata: "JNB", city: "Johannesburg", country: "South Africa", region: "Africa" },
  { iata: "CAI", city: "Cairo", country: "Egypt", region: "Africa" },
  { iata: "NBO", city: "Nairobi", country: "Kenya", region: "Africa" },
  { iata: "ADD", city: "Addis Ababa", country: "Ethiopia", region: "Africa" },
  { iata: "CMN", city: "Casablanca", country: "Morocco", region: "Africa" },
] as const;

/** Phrases a user might type that mean a whole region. */
export const REGION_SYNONYMS: Record<string, Region> = {
  asia: "Asia",
  "east asia": "Asia",
  "southeast asia": "Asia",
  "south asia": "Asia",
  "middle east": "Asia",
  europe: "Europe",
  "western europe": "Europe",
  "eastern europe": "Europe",
  africa: "Africa",
  oceania: "Oceania",
  australia: "Oceania",
  "australia and new zealand": "Oceania",
  "south pacific": "Oceania",
  "south america": "South America",
  "latin america": "South America",
  "north america": "North America",
  caribbean: "North America",
};

/** Cities whose name differs from common usage. */
export const CITY_ALIASES: Record<string, string> = {
  nyc: "new york",
  "new york city": "new york",
  sf: "san francisco",
  "bay area": "san francisco",
  la: "los angeles",
  dc: "washington",
  "washington dc": "washington",
  cdmx: "mexico city",
};
